### YamlMime:Landing
title: 'Documentación de los roles de Azure AD: Azure AD'
summary: El control de acceso basado en rol de Azure AD administra el acceso a los recursos de Azure AD. Cree roles personalizados, asigne roles que usan unidades administrativas para restringir el ámbito de control, asigne el acceso de las aplicaciones a grupos o usuarios, administre la elegibilidad con Privileged Identity Management (PIM) o delegue los permisos para distribuir las tareas de administración de identidades.
metadata:
  title: Documentación de los roles de Azure Active Directory
  description: Aprenda a usar los roles de Azure AD para administrar el acceso en su organización.
  services: active-directory
  ms.service: active-directory
  ms.subservice: roles
  manager: daveba
  ms.topic: landing-page
  ms.date: 10/19/2020
  author: curtand
  ms.author: curtand
  ms.openlocfilehash: 8dd6ac6fef0dbc84c77ccacfd048b2af21771f6a
  ms.sourcegitcommit: d60976768dec91724d94430fb6fc9498fdc1db37
  ms.translationtype: HT
  ms.contentlocale: es-ES
  ms.lasthandoff: 12/02/2020
  ms.locfileid: "96499210"
landingContent:
- title: Acerca de los roles de Azure AD
  linkLists:
  - linkListType: overview
    links:
    - text: Introducción al control de acceso basado en rol de Azure AD
      url: custom-overview.md
  - linkListType: concept
    links:
    - text: Descripción de los roles de Azure AD
      url: concept-understand-roles.md
    - text: Descripción de las unidades administrativas de Azure AD
      url: administrative-units.md
    - text: Uso de grupos en la nube para administrar asignaciones de roles
      url: groups-concept.md
- title: Introducción
  linkLists:
  - linkListType: quickstart
    links:
    - text: Concesión de permisos para crear registros de aplicaciones ilimitados
      url: quickstart-app-registration-limits.md
- title: Delegación de roles
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: Delegación de roles por tarea
      url: delegate-by-task.md
    - text: Delegación de la administración de aplicaciones
      url: delegate-app-roles.md
- title: Asignación de roles a usuarios
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: Creación de roles personalizados
      url: custom-create.md
    - text: Asignación de roles mediante Graph API
      url: custom-assign-graph.md
    - text: Asignación mediante PowerShell
      url: custom-assign-powershell.md
    - text: Asignación de roles mediante Graph API
      url: custom-assign-graph.md
- title: Asignación de roles a grupos
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: Creación de grupos a los que se pueden asignar roles
      url: groups-create-eligible.md
    - text: Asignación de un rol a un grupo en la nube
      url: groups-assign-role.md
    - text: Hacer que un grupo sea válido para PIM
      url: groups-pim-eligible.md
    - text: Visualización de las asignaciones de un grupo
      url: groups-view-assignments.md
- title: Administración del ámbito con las unidades administrativas
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: Adición y eliminación de unidades administrativas
      url: admin-units-manage.md
    - text: Asignación de usuarios a unidades
      url: admin-units-add-manage-users.md
    - text: Asignación de grupos a unidades
      url: admin-units-add-manage-groups.md
    - text: Asignación de grupos con ámbito
      url: admin-units-assign-roles.md
